services:
  ml-model:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PORT=8000
    volumes:
      - .:/app
      - /app/__pycache__
    networks:
      - ml-network
    restart: unless-stopped


networks:
  ml-network:
    driver: bridge 