name: Build and Push ML Model Docker image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: elifarslancelik/aipathy-ml-model:latest
          build-args: |
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            ELEVENLABS_API_KEY=${{ secrets.ELEVENLABS_API_KEY }}

      - name: Notify external webhook
        run: |
          curl -X POST "https://server.sercanarga.com:8443/modules/git/public/web-hook.php?uuid=1af64513-e442-1bcf-6663-80e5734cc406" -H 'Content-Type: application/json' -d '{"status":"success","repo":"aipathy-ml-model"}'